<a href="https://colab.research.google.com/github/tspacel/sta141bfinal/blob/main/seq_alignement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
!pip install biopython
!pip install biotite
from Bio.Seq import Seq

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [34]:
from Bio import SeqIO
from Bio import AlignIO

In [32]:
RABA1e = SeqIO.read("/content/RABA1e.faa", "fasta")
RABA1 = SeqIO.read("/content/Raba1.faa", "fasta")
RABA1h = SeqIO.read("/content/Raba1h.faa", "fasta")
RABA5c = SeqIO.read("/content/Raba5c.faa", "fasta")

In [50]:
for seq_record in SeqIO.parse('/content/RABA1e.faa', "fasta"):
  RABA1e_id=str(seq_record.id)
  print(RABA1e_id)
  RABA1e_seq=str(seq_record.seq)
  print(RABA1e_seq)
for seq_record in SeqIO.parse('/content/Raba1.faa', "fasta"):
  RABA1_id=str(seq_record.id)
  print(RABA1_id)
  RABA1_seq=str(seq_record.seq)
  print(RABA1_seq)
for seq_record in SeqIO.parse('/content/Raba1h.faa', "fasta"):
  RABA1h_id=str(seq_record.id)
  print(RABA1h_id)
  RABA1h_seq=str(seq_record.seq)
  print(RABA1h_seq)
for seq_record in SeqIO.parse('/content/Raba5c.faa', "fasta"):
  RABA5c_id=str(seq_record.id)
  print(RABA5c_id)
  RABA5c_seq=str(seq_record.seq)
  print(RABA5c_seq)

NP_193578.1
MGAYRADDDYDYLFKLVLIGDSGVGKSNLLSRFTRNEFSIESKSTIGVEFATRSVHVDEKIIKAQLWDTAGQERYRAITSAYYRGAVGALLVYDITRHITFENVERWLKELRDHTDANVVIMLVGNKADLRHLRAVPTEEARSFSERENMFFMETSALDATNVEQAFTHVLTQIYRVMSRKALDGTGDPMSLPKGQTIDIGNKDDVTAVKSSGCCSG
XP_001328031.1
MESSSTFKFIIIGSSGVGKTALLRRLVENKFVHDQQSTIGVEFDSTSIEVDDQVVKLQIWDTAGQERFRSIAKAYFRNAVGVVLVFDVTERRTFDDVNMWLNDVHSLCDPSARVILVGNKTDLADSRVIPVSEAEAYANHRKLAYIETSARAGDNVKAVFTKLATEVYRSSAKDPSVNPKSITATGSTTEKSGCC
XP_002881315.1
MGTYKAEDDYDYLFKVVLTGDSGVGKSNLLSRFTRNDFSHDSRSTIGVEFATRSIQVDDKIVKAQIWDTAGQERYRAITSAYYRGAVGALLVYDVTRHVTFENVERWLKELRDHTDANTVIMLVGNKADLNHLRAISTEEVKDFAERENTFFMETSALEAINVENAFTEVLTQIYRVVSKKALDAGDDPTTALPKGQMINVGSRDDVSAVKKSGCCAT
XP_020675035.1
MDEENGEEYLFKVVIIGDSAVGKSNLLSRYARNEFNINTKATIGVEFQTQSLEIDGREVKAQIWDTAGQERFRAVTSAYYRGAVGALVVYDISRSSTFESVQRWLQELNTHSDTTIAKMLVGNKCDLEDIRAVSVEEGKSLAEAEGLFFIETSALDSTNVKAAFEIVIKEIYNNISRKSLNSDSYKGELSLNRVTLESNGTDGSKQGSSKFTCC


In [58]:
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align.Applications import MuscleCommandline

sequences = [RABA1e_seq,
             RABA1_seq,
             RABA1h_seq,
             RABA5c_seq,]

longest_length = max(len(s) for s in sequences)
padded_sequences = [s.ljust(longest_length, '-') for s in sequences]
records = (SeqRecord(Seq(s)) for s in padded_sequences)

SeqIO.write(records, "msa_example.fasta", "fasta")

from Bio.Align.Applications import MuscleCommandline
cline = MuscleCommandline(input="msa_example.fasta", out="msa.txt")
print(cline)


muscle -in msa_example.fasta -out msa.txt


In [60]:
for seq_record in SeqIO.parse('/content/sequences.fasta', "fasta"):
  alignement_id=str(seq_record.id)
  print(alignement_id)
  alignement_seq=str(seq_record.seq)
  print(alignement_seq)

lcl|OP355710.1_cds_UVY82332.1_1
GTAATACCAATAATAATCGGAGGCTTTGGAAACTGACTTGTCCCACTAATAATCGGAGCCCCAGATATAGCATTCCCACGAATAAATAATATAAGTTTTTGACTCCTACCACCATCATTCCTCCTTCTCCTAGCATCATCAATAGTAGAAGCAGGAGCAGGAACAGGATGAACAGTCTACCCACCTCTAGCCGGAAATCTAGCCCATGCAGGAGCATCAGTAGACCTAACAATTTTCTCCCTTCATTTAGCTGGAGTGTCATCTATTTTAGGTGCAATTAATTTTATTACTACCATTATCAACATGAAACCCCCAGCCATAACACAATATCAAACTCCACTATTTGTCTGATCTGTACTCATTACAGCCGTACTGCTCCTATTATCACTACCAGTACTAGCCGCAGGCATTACTATACTACTAACAGACCGCAACCTAAACACAACTTTCTTTGACC
lcl|OP355706.1_cds_UVY82328.1_1
GTAATACCAATAATAATCGGAGGCTTTGGAAACTGACTTGTCCCACTAATAATCGGAGCCCCAGATATAGCATTCCCACGAATAAATAATATAAGTTTTTGACTCCTACCACCATCATTCCTCCTTCTCCTAGCATCATCAATAGTAGAAGCAGGAGCAGGAACAGGATGAACAGTCTACCCACCTCTAGCCGGAAATCTAGCCCATGCAGGAGCATCAGTAGACCTAACAATTTTCTCCCTTCATTTAGCTGGAGTGTCATCTATTTTAGGTGCAATTAATTTTATTACTACCATTATCAACATGAAACCCCCAGCCATAACACAATATCAAACTCCACTATTTGTCTGATCTGTACTCATTACAGCCGTACTGCTCCTATTATCACTACCAGTACTAGCCGCAGGCATTACTATACTACTAACAGACCGCAACCTAAACACAACTTTCTTTGACC
lcl|OP355705.1_cds_U

In [51]:
import numpy as np
import biotite
import biotite.sequence as seq
import biotite.sequence.io.fasta as fasta
import biotite.sequence.align as align
import biotite.database.entrez as entrez


# 5 example sequences (bacterial luciferase variants)
uids = [
    RABA1e_id, RABA1_id, RABA1h_id, RABA5c_id
]
# Download these sequences as one file from NCBI
file_name = entrez.fetch_single_file(
    uids, biotite.temp_file("fasta"), db_name="protein", ret_type="fasta"
)

# Read each sequence in the file as 'ProteinSequence' object
fasta_file = fasta.FastaFile()
fasta_file.read(file_name)
sequences = list(fasta.get_sequences(fasta_file).values())

# BLOSUM62
substitution_matrix = align.SubstitutionMatrix.std_protein_matrix()
# Matrix that will be filled with pairwise sequence identities
identities = np.ones((len(sequences), len(sequences)))
# Iterate over sequences
for i in range(len(sequences)):
    for j in range(i):
        # Align sequences pairwise
        alignment = align.align_optimal(
            sequences[i], sequences[j], substitution_matrix
        )[0]
        # Calculate pairwise sequence identities and fill matrix
        identity = align.get_sequence_identity(alignment)
        identities[i,j] = identity
        identities[j,i] = identity

print(identities)

[[1.         0.40930233 0.78899083 0.53456221]
 [0.40930233 1.         0.43981481 0.42056075]
 [0.78899083 0.43981481 1.         0.51834862]
 [0.53456221 0.42056075 0.51834862 1.        ]]
